RailsCanCan
allrom/RoRPro pull request #10
Opened 2019-10-29 14:05 UTC by allrom

2019-10-30 07:59 UTC, aishek requested changes

2019-10-30 07:59 UTC, aishek commented on app/models/ability.rb
> +    end
Можно красиво разрулить "особым случаем":
```
return guest_permissions unless user
user.admin? ? admin_permissions : user_permissions
```

2019-10-30 07:59 UTC, aishek commented on app/models/ability.rb
> +      !(user.author?(resource) || resource.voted?(user))
Сложно получилось. Упростить можно написав в две строки:
```
do |resource|
  next false if user.author?(resource)
  !resource.voted?(user)
end
```

2019-10-30 07:59 UTC, aishek commented on app/views/answers/_answer.html.slim
> +  - if can?(:update, question) && !answer.best?
Лучше отдельную привелегию завести

2019-10-31 08:28 UTC, aishek requested changes
Надо поправить партиал ответа

2019-10-31 08:28 UTC, aishek commented on app/views/answers/_answer.html.slim
> +  - if can?(:be_an_author, question) && !answer.best?
Может я туплю: почему тут не использовать `- if can?(:flag_best, question)`?

2019-10-31 08:28 UTC, aishek commented on app/views/answers/_answer.html.slim
> +  - if can?(:modify, answer) && answer.persisted?
Это к одному из прошлых заданий, но тут хочется убрать проверку `answer.persisted?`

2019-10-31 12:18 UTC, aishek requested changes
У меня есть вопросы

2019-10-31 12:18 UTC, aishek commented on app/views/answers/_answer.html.slim
> +  - if can?(:flag_best, answer) && !answer.best?
А вторая часть проверки зачем?

2019-10-31 12:18 UTC, aishek commented on app/views/answers/_answer.html.slim
> +  - if can?(:modify, answer)
Хорошо, а что будет если в форме создания ответа не заполнить текст и кликнуть кнопку создания?

2019-10-31 12:30 UTC, allrom commented on app/views/answers/_answer.html.slim
> +  - if can?(:modify, answer)
Рендерятся ошибки на пустое / слишком короткое поле 'body'.
что должно быть?

2019-10-31 12:33 UTC, allrom commented on app/views/answers/_answer.html.slim
> +  - if can?(:flag_best, answer) && !answer.best?
Кнопка 'best!'  появляется рядом с ответом, который и так 'Best' , это неправильно.

2019-11-01 08:45 UTC, aishek approved these changes

2019-11-04 11:33 UTC, merged