Cache
allrom/RoRPro pull request #14
Opened 2019-12-11 14:08 UTC by allrom

2019-12-11 21:05 UTC, aishek requested changes

2019-12-11 21:05 UTC, aishek commented on app/views/answers/_answer.html.slim
> +  - cache answer do
Если я правильно понял, то тут под ключём кэширования ещё и пользователь. Что будет, если включить кэширование, посмотреть ответ сначала залогиненым пользователем, а затем гостем?

2019-12-11 21:05 UTC, aishek commented on app/views/answers/_form.html.slim
> +- cache [ 'answers_form', model ] do
Что будет, если попробовать сохранить ответ с ошибкой, а затем зайти на форму заново?

2019-12-11 21:05 UTC, aishek commented on app/helpers/application_helper.rb
> +  def collection_cache_key_for(object)
А для чего этот метод?

2019-12-11 21:05 UTC, aishek commented on app/views/questions/show.html.slim
> +- cache question do
Что будет если зайти на эту страницу сначала гостем, а затем автором вопроса?

2019-12-12 10:28 UTC, allrom commented on app/views/answers/_answer.html.slim
> +  - cache answer do
Просмотрел проблему, спасибо. Постарался исправить (в след. коммит).

2019-12-12 10:30 UTC, allrom commented on app/views/answers/_form.html.slim
> +- cache [ 'answers_form', model ] do
Рендерятся ошибки и т.д., работает штатно. После исправления получается , например, два разных польз. работают с одной кешир. формой. Вроде это позитивно , или я что-то недопонимаю?

2019-12-12 10:33 UTC, allrom commented on app/helpers/application_helper.rb
> +  def collection_cache_key_for(object)
Из скринкаста, посмотрел как работает в question index, оставил для истории. Т.к. для rails 5 нашел более интересный метод 'cache collection'

2019-12-12 16:17 UTC, aishek approved these changes
Как решение задания норм.

Можно было ещё под кэш вынести не весь шаблон, а только те части, которые не зависят от текущего пользователя.

Как альтернативное решение: добавить в ключ кэширования текущего пользователя `- cache [answer, current_user]`

2019-12-12 20:41 UTC, merged