Ajax
allrom/RoRPro pull request #4
Opened 2019-08-23 13:15 UTC by allrom

2019-08-23 13:46 UTC, aishek requested changes

2019-08-23 13:46 UTC, aishek commented on app/controllers/answers_controller.rb
> +    @answer = question.answers.create(answer_params.merge(user: current_user))
А что если добавится валидация в ответ и они не создасться на самом деле?

2019-08-23 13:46 UTC, aishek commented on app/controllers/questions_controller.rb
> +    @question = current_user.questions.create(question_params)
Что если вопрос не создасться?

2019-08-23 13:46 UTC, aishek commented on app/models/answer.rb
> +    self.toggle(:best).save
Тогда уж лучше использовать https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-toggle-21 `toggle!(:best)`

2019-08-23 13:46 UTC, aishek commented on app/models/answer.rb
> +    Answer.where(question_id: question_id, best: true).update_all(best: false)
Тут не хватается транзакции. И код можно упростить: `question.answers.where(best: true).update_all(best: false)`

2019-08-23 13:46 UTC, aishek commented on app/views/answers/_answer.html.slim
> +  - if current_user&.author?(question) && !answer.best
Для булевых атрибутов создаются также методы со знаком вопроса в конце, надо их использовать `answer.best?`

2019-08-23 13:46 UTC, aishek commented on app/views/questions/_question.html.slim
> +  td class= "table-data"= question.id
В slim можно короче: `td.table-data = question.id`

2019-08-23 13:46 UTC, aishek commented on app/views/questions/_questions.html.slim
> +- questions.each do |q|
Должна сработать короткая версия: `render questions`

2019-08-23 13:46 UTC, aishek commented on spec/acceptance/answer/best_answer_spec.rb
> +  describe 'Author', js: true do
Надо проверить не автора и гостя

2019-08-23 13:46 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +      before { patch :flag_best, params: { id: visitor_answer }, format: :js}
Лучше не писать тестируемое действие в `before`. `before` — для подготовки к тесту.

2019-08-23 13:46 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +  describe 'PATCH #flag_best' do
И надо проверить гостя

2019-08-23 13:46 UTC, aishek commented on spec/models/answer_spec.rb
> +  describe '#mark_best' do
И надо порядок проверить тестом

2019-08-26 06:36 UTC, aishek approved these changes

2019-08-26 06:36 UTC, aishek commented on app/controllers/answers_controller.rb
> +    @answer = question.answers.create(answer_params.merge(user: current_user))
Лучше как-то поближе к коду, который выдают генераторы:

```
@answer = question.answers.build(answer_params.merge(user: current_user))
if @answer.save
  flash.now[:notice] = "Answer added."
else
  flash.now[:error] = "Answer not added."
  render :create
end
```

2019-08-26 06:36 UTC, aishek commented on app/models/answer.rb
> +    Answer.transaction do
Можно просто
```
transaction do
  # ...
end
```

2019-08-26 06:36 UTC, aishek commented on app/models/answer.rb
> +    !best
Бесполезный метод. Лучше так и писать — `!answer.best?`, `unless answer.best?`

2019-08-26 06:36 UTC, aishek commented on app/views/answers/_answer.html.slim
> +  - if answer.best
Читабельнее будет `- if answer.best?`

2019-08-26 06:38 UTC, aishek commented
Хорошее решение с `toggle!`, везде исправлены css-классы в slim и очень понятный и читаемый тест на порядок.

Спасибо!

2019-08-26 06:44 UTC, allrom commented
> Хорошее решение с `toggle!`, везде исправлены css-классы в slim и очень понятный и читаемый тест на порядок.
> 
> Спасибо!

Александр, тебе огромное спасибо!

2019-08-26 07:42 UTC, merged

2019-08-26 08:08 UTC, aishek commented on app/models/answer.rb
> +    transaction do
Тут я поспешил. Есть две проблемы.

Во-первых, мы полагаемся на то, что метод не будет вызван для лучшего ответа. А если это всё-таки случиться, то метод снимет отметку лучшего с нашего ответа, что странно.

Во-вторых, между 12 и 13 строками в некоторых БД может возникнуть ситуация, когда другой поток прочитает данные из БД как будто в них нет лучшего ответа, а мы так не хотим.

Исправить так:

```
with_lock do
  question.answers.where(best: true).update_all(best: false)
  update!(best: true)
end
```

`with_lock` делает `SELECT FOR UPDATE` https://postgrespro.ru/docs/postgresql/9.6/explicit-locking для ответа, и таким образом с одной стороны этот селект не стартанёт пока все изменения из других потоков к этой строке не применятся, с другой стороны пока транзакция не завершится другим потокам нельзя будет ни читать, ни писать в эту строку.

`update!(best: true)` позволяет нам без дополнительного кода игнорировать случай, когда метод вызван на лучшем ответе.