ActiveStorage
allrom/RoRPro pull request #5
Opened 2019-08-31 18:06 UTC by allrom

2019-09-01 06:22 UTC, aishek requested changes
Хорошая идея с shared-вьюшкой для просмотра аттачментов.

Нужен ещё один подход к снаряду.

2019-09-01 06:22 UTC, aishek commented on app/controllers/attachments_controller.rb
> +    @file = ActiveStorage::Attachment.find(params[:id])
Не хватает проверки на авторство

2019-09-01 06:22 UTC, aishek commented on spec/controllers/attachments_controller_spec.rb
> +  describe 'DELETE #destroy' do
Нужно добавить тесты на удаление файла не своего вопроса или ответа

2019-09-01 06:22 UTC, aishek commented on app/models/answer.rb
> +  has_many_attached :files
Не хватает юнит-теста на эту строку

2019-09-02 08:01 UTC, aishek approved these changes

2019-09-02 08:01 UTC, aishek commented on app/controllers/attachments_controller.rb
> +    @file = ActiveStorage::Attachment.find(params[:id])
Почему тут не использовать метод модели пользователя?

2019-09-02 08:53 UTC, vkurennov approved these changes

2019-09-02 08:53 UTC, vkurennov commented on app/controllers/attachments_controller.rb
> +    if resource.user == current_user
у тебя есть метод в модели User, который делает такую проверку, причем более оптимально. используй его.

2019-09-02 13:20 UTC, merged