NestedForms&Poly
allrom/RoRPro pull request #6
Opened 2019-09-09 15:26 UTC by allrom

2019-09-10 07:48 UTC, aishek requested changes
Нужно исправить просмотр наград в сторону упрощения, и вынести назначение награды в метод пометки лучшего ответа.

2019-09-10 07:48 UTC, aishek commented on app/controllers/links_controller.rb
> +  private
Весь код начиная с этой строки можно удалить. Это тот самый случай, когда чем меньше кода, тем читабельнее

2019-09-10 07:48 UTC, aishek commented on spec/controllers/links_controller_spec.rb
> +  let!(:visitor_answer_w_link) {
В итоге тут все сущности `_w_link`. Если убрать этот постфикс в идентификаторах, то станет чище

2019-09-10 07:48 UTC, aishek commented on spec/controllers/links_controller_spec.rb
> +        expect(user_question_w_link.links.count).to eq(0)
Какая связь между этой проверкой и названием теста?

2019-09-10 07:48 UTC, aishek commented on spec/factories/answers.rb
> +      after(:create) do |a|
Даже в таких случаях лучше название переменной не сокращать

2019-09-10 07:48 UTC, aishek commented on spec/factories/questions.rb
> +      after(:create) do |q|
Тут тоже лучше название переменной не сокращать

2019-09-10 07:48 UTC, aishek commented on spec/support/rspec_matcher.rb
> +RSpec::Matchers.define :validate_url_of do |attribute|
А этот код где-то используется?

2019-09-10 07:48 UTC, aishek commented on app/views/shared/_links.html.slim
> +            - if link.url =~ /^(?i)https:\/\/gist\.github\.com\/(?=.{1,39}$)(?![_\W])[a-z0-9-]+(?<![_\W])\/([a-z0-9\/.]+)$/
Этой проверке не место во вьюшке

2019-09-10 07:48 UTC, aishek commented on app/views/shared/_awards.html.slim
> +#awards-given.hidden
При таком подходе приходится проверять, что пользователь залогинен, писать js для показа-сокрытия списка наград, рендерить этот список на каждой странице, даже если его не понадобится покащывать.

Надо проще: завести отдельный контроллер, и переходит на его экшн просто по ссылке.

2019-09-10 07:48 UTC, aishek commented on app/views/answers/_answer.html.slim
> +    td.table-view-l = link_to 'Links', answer_links_path(answer),
Зачем такая сложность? Почему сразу ссылки не показать?

2019-09-10 07:48 UTC, aishek commented on app/views/answers/_answer.html.slim
> +    td.table-view-f = link_to 'Files', answer_path(answer),
Зачем такая сложность?

2019-09-10 07:48 UTC, aishek commented on app/controllers/answers_controller.rb
> +      award.update!(user: answer.user) if award
Это должно быть частью метода пометки лучшим

2019-09-10 07:48 UTC, aishek commented on spec/acceptance/question/link_allow_delete_spec.rb
> +      expect(page).not_to have_content authors_q_w_link.links.first.name
Ещё бы перед кликом проверить что текст был на странице

2019-09-10 07:48 UTC, aishek commented on spec/acceptance/question/link_allow_delete_spec.rb
> +  given!(:visitors_q_w_link) { create :question, :with_link, user: visitor }
Постфиксы в названии лишние

2019-09-10 07:48 UTC, aishek commented on app/models/award.rb
> +  validates :name, :image_filename, presence: true
Почему файл не через ActiveStorage?

2019-09-11 15:13 UTC, aishek requested changes
Нужно ещё чуть подкрутить детали

2019-09-11 15:13 UTC, aishek commented on app/models/answer.rb
> +    award.update!(user: user) if award
Всё правильно, только это должно быть частью транзакции по условию задачи

2019-09-11 15:13 UTC, aishek commented on app/views/shared/_nav.html.slim
> +        - unless current_user.awards.empty?
Ссылку лучше показывать безусловно — так на один запрос к базе меньше

2019-09-11 15:13 UTC, aishek commented on spec/models/answer_spec.rb
> +    let!(:award) { Award.create(id: 1, name: 'TestAward', question_id: 1) }
А зачем указывать идентификаторы?

2019-09-11 15:13 UTC, aishek commented on spec/factories/answers.rb
> +    trait :with_link do
Такое же название, что и в 19 строке

2019-09-11 15:13 UTC, aishek commented on app/helpers/links_helper.rb
> +  def gist_url?(url)
Хорошо бы покрыть тестами

2019-09-12 08:46 UTC, aishek requested changes
Надо исправить тесты хелпера, всё остальное у меня не вызывает вопросов.

2019-09-12 08:46 UTC, aishek commented on app/models/answer.rb
> +  def award
Спорный метод. В смысле метод есть, а польза неочевидна

2019-09-12 08:46 UTC, aishek commented on spec/helpers/url_match_spec.rb
> +  let(:gist_matcher) { /^(?i)https:\/\/gist\.github\.com\/(?=.{1,39}$)(?![_\W])[a-z0-9-]+(?<![_\W])\/([a-z0-9\/.]+)$/ }
Так категорически делать нельзя: копировать реализацию и тестировать её, надеясь что она совпадает с телом метода. Самый полезный принцип тестирования — тестирование чёрного ящика.

Исправить можно двумя способами: или не использовать форму предикатного матчера, или заинклюдить хэлпер прямо в тест. Но совершенно точно нужно вызывать метод хелпера, и проверять результат именно его вызова.

2019-09-12 19:08 UTC, aishek requested changes
Опять тот же недочёт с хелпером.

2019-09-12 19:08 UTC, aishek commented on spec/helpers/url_match_spec.rb
> +  include LinksHelper
Это норм

2019-09-12 19:08 UTC, aishek commented on spec/helpers/url_match_spec.rb
> +module LinksHelper
А вот это не норм. Опять копирование, только с другого боку. Нужно зареквайрить хелпер, да и всё.

2019-09-13 19:34 UTC, aishek approved these changes

2019-09-14 08:58 UTC, vkurennov approved these changes

2019-09-16 13:27 UTC, merged